### ISSUE TITLE
[Server/Apicurio] Bean-validated scalar path parameter type not generated after 2.20.0 (full $ref resolution before Apicuro codegen)

### ISSUE THREAD

**Issue by robert-istvan** [quarkiverse/quarkus-openapi-generator#1784]
### Tell us the extension you're using

Client

### I tried this:

Since 2.20.0 (regression introduced by #1599, "Enhance OpenAPI code generation with multi-spec support"),
the Apicurio server generator (`quarkus.openapi.generator.use-apicurio`, the default) fully resolves the
OpenAPI document via `OpenAPI3Parser` with `resolveFully(true)` before handing it to Apicurio's own
`OpenApi2JaxRs` codegen (see `ApicurioOpenApiServerCodegen#resolveToJSON`). In 2.19.0 and earlier, the
document was only YAML->JSON converted (`convertToJSON`), with `$ref`s left intact.

### This happened:

When `quarkus.openapi.generator.use-bean-validation=true` and a path parameter's schema is a constrained scalar (e.g. `type: integer, format: int64, minimum: 0`) referenced via a named `components/schemas` entry, Apicurio synthesizes a validated wrapper type for the parameter (e.g. `Int64Id`) and references it in the generated JAX-RS resource interface, but the corresponding bean class is no longer generated at all. This happens identically whether the schema is `$ref`'d or written inline, because full resolution collapses `$ref`s before Apicurio's codegen ever runs – so there's no spec-level workaround.

Result: generated sources fail to compile with `cannot find symbol` for the wrapper class.

### I expected this:

The generated JAX-RS resource and its referenced bean-validated parameter wrapper class stay consistent – either both are generated (as in 2.19.0), or the parameter type falls back to a primitive/no wrapper is referenced.

### Steps to reproduce

1. Use an OpenAPI spec with a path parameter such as:

```
paths:
  /items/{itemId}:
    get:
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Int64Id'
      responses:
        '200': { description: OK }
components:
  schemas:
    Int64Id:
      type: integer
      format: int64
      minimum: 0
```

2. application.properties:

```
quarkus.openapi.generator.spec=my-api.yaml
quarkus.openapi.generator.use-bean-validation=true
```

3. Build with quarkus-openapi-generator-server <= 2.19.0 – compiles fine, Int64Id.java is generated
under generated/.../beans/Int64Id.java.

4. Bump to >= 2.20.0 or later (tested through 2.23.0) with no other changes – build fails:
```
error: cannot find symbol
import au.org.sirca.remedy.api.generated.beans.Int64Id;
...
`Int64Id.java` is not present anywhere in the generated sources.
```

**Actual behavior**

The resource interface still requires the wrapper class name, but the wrapper class itself is not emitted, causing a compile-time cannot find symbol error. This is a full regression (build-breaking) for any specusing bean-validated scalar path parameters with the Apicurio server engine.

**Expected behavior**

The generated JAX-RS resource and its referenced bean-validated parameter wrapper class stay consistent – either both are generated (as in 2.19.0), or the parameter type falls back to a primitive/no wrapper is referenced.

### Anything else?

**Suspected cause**

ApicurioOpenApiServerCodegen#resolveToJSON (added by #1599) uses ParseOptions.setResolveFully(true) before delegating to Apicurio's OpenApi2JaxRs. This changes what Apicurio's own codegen sees (no named $refs left for scalar aliases), but Apicurio's bean-validation naming logic for path parameters was not updated to match, producing a mismatch between the referenced type name and the (missing) generated class.

### Output of `java -version`

25

### Quarkus OpenApi version or git rev

2.20.0-2.23.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 9.6.1

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.name: Bug Report 🐞
