### ISSUE TITLE
Cannot find symbol "NOT_FOUND.class"

### ISSUE THREAD

**Issue by david-cabillic** [quarkiverse/quarkus-openapi-generator#852]
During generation with 2.6.0-lts (or 2.5.0) from an Open API JSON file, a NOT_FOUND.class is included in annotations but **not imported** :

```java
@com.fasterxml.jackson.annotation.JsonSubTypes({
    @com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = NOT_FOUND.class, name = "ArchivalAutoFillExpansion"),
    @com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = NOT_FOUND.class, name = "ReindexAutoFillExpansion"),
    @com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = NOT_FOUND.class, name = "ArchivalAutoFillExpansionModifierProperties"),
    @com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = NOT_FOUND.class, name = "ReindexAutoFillExpansionModifierProperties"),
})
```

It was working with 2.4.7.

**Comment by ricardozanini** [comment]
Hi! Thanks for reporting it, but we will need more info.

Can you please share a reproducer?

**Comment by david-cabillic** [comment]
Hi,

It's not easy to provide a reproducer cause I have few time and my code is in a custom company framework. This is my config :

pom.xml
`
<properties>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>3.16.2</quarkus.platform.version>
        <quarkus-maven-plugin.version>3.16.2</quarkus-maven-plugin.version>
</properties>
<dependencies>
        <dependency>
            <groupId>io.quarkiverse.openapi.generator</groupId>
            <artifactId>quarkus-openapi-generator</artifactId>
            <version>2.6.0-lts</version>
        </dependency>
</dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>io.smallrye</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <version>3.1.6</version>
                <executions>
                    <execution>
                        <id>make-index</id>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
`

application.properties
`
quarkus.openapi-generator.codegen.enable-security-generation=false
quarkus.openapi-generator.codegen.spec.administration_json.base-package=ch.tcs.onbase.administration
quarkus.openapi-generator.codegen.spec.administration_json.config-key=obadministration
quarkus.openapi-generator.codegen.spec.administration_json.additional-api-type-annotations=@org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders(ch.tcs.onbase.header.AuthHeadersFactory.class)
quarkus.openapi-generator.codegen.spec.administration_json.model-name-prefix=OB`

[administration.json](https://github.com/user-attachments/files/17803327/administration.json)

**Comment by david-cabillic** [comment]
@ricardozanini  Maybe you should activate security and remove 'quarkus.openapi-generator.codegen.spec.administration_json.additional-api-type-annotations'.
