### PR TITLE
Fix #824 - Introduce a separated OIDC module to hold security dependencies

### LINKED ISSUE #824: Build fails if `quarkus-oidc-client` is not in the classpath
As part of the build generation introduced in #795, the latest release now breaks projects that are not using OIDC:

```
[ERROR] Failed to execute goal com.redhat.quarkus.platform:quarkus-maven-plugin:3.8.4.redhat-00002:build (default) on project openapi-bug: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkiverse.openapi.generator.deployment.GeneratorProcessor#additionalBean threw an exception: java.lang.NoClassDefFoundError: io/quarkus/oidc/client/runtime/AbstractTokensProducer
[ERROR]         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR]         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:508)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
[ERROR]         at io.quarkiverse.openapi.generator.deployment.GeneratorProcessor.additionalBean(GeneratorProcessor.java:72)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.ClassNotFoundException: io.quarkus.oidc.client.runtime.AbstractTokensProducer
[ERROR]         at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:210)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:205)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
[ERROR]         ... 16 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

This openAPI spec doesn't even have `security` tags, so all the authz classes should be skipped and not generated.

### PR DESCRIPTION
**Pull request by ricardozanini**
Fix #824 

In this PR:

- Removed references of OIDC libraries from the main `runtime` module
- I created a separate `quarkus-openapi-generator-oidc` component to hold OIDC use cases; users now MUST add this new dependency to their project in case OIDC is required.
- Review the `integration-tests` module to remove OIDC from every module; just add to `security` where it's really required.
- Updated documentation.

Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [x] Pull Request contains link to the issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to backport the original PR to the `quarkus2` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by Postremus** [comment]
works for me, quarkus starts now with quarkus-hibernate-validator.

**Review by mcruzdev — APPROVED** [review]

**Comment by ricardozanini** [comment]
@gastaldi do I have to do anything else to release the new module?

File: client/integration-tests/security/pom.xml [hunk 1]
```diff
@@ -91,5 +95,30 @@
         <quarkus.package.type>native</quarkus.package.type>
       </properties>
     </profile>
+    <profile>
+      <id>resteasy-reactive</id>
```
Comment (gastaldi) [inline client/integration-tests/security/pom.xml:99]: Maybe just `rest` given that the artifact is `quarkus-rest` (we dropped the reactive some versions ago)

**Comment by gastaldi** [comment]
@ricardozanini you can use conditional dependencies to have your module added automatically when `quarkus-oidc` is available

**Comment by gastaldi** [comment]
> @gastaldi do I have to do anything else to release the new module?

No, it should work as usual

**Review by fjtirado — APPROVED** [review]

File: client/integration-tests/security/pom.xml (hunk 1 above)
Comment (hbelmiro) [reply client/integration-tests/security/pom.xml:99]: That's just the profile name that we use for tests.
It would be nice to rename them though. But maybe it would be better to do it in a specific PR.

**Comment by ricardozanini** [comment]
> @ricardozanini you can use conditional dependencies to have your module added automatically when `quarkus-oidc` is available: https://quarkus.io/guides/conditional-extension-dependencies

oh nice! I'll do that then :D

**Comment by ricardozanini** [comment]
After reviewing the code base to add these conditionals, I'd have to create a new `oidc` extension and two additional modules, `auth` and `config`, to support this use case. Then, move all the authentication-related generation codes to `auth` and the OIDC to `oidc`. We would end up with five additional modules.

It's unnecessary to add all this complexity to the code base at this moment. OIDC support will work if users can add the new module we introduced today to their dependencies.

This new way of generating authentication classes did more harm than good. This rework should have been done in the original PR, but I don't have time to implement it now. If someone from the community is interested, please let me know.
