### ISSUE TITLE
Build fails if `quarkus-oidc-client` is not in the classpath

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#824]
As part of the build generation introduced in #795, the latest release now breaks projects that are not using OIDC:

```
[ERROR] Failed to execute goal com.redhat.quarkus.platform:quarkus-maven-plugin:3.8.4.redhat-00002:build (default) on project openapi-bug: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkiverse.openapi.generator.deployment.GeneratorProcessor#additionalBean threw an exception: java.lang.NoClassDefFoundError: io/quarkus/oidc/client/runtime/AbstractTokensProducer
[ERROR]         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR]         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:508)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
[ERROR]         at io.quarkiverse.openapi.generator.deployment.GeneratorProcessor.additionalBean(GeneratorProcessor.java:72)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.ClassNotFoundException: io.quarkus.oidc.client.runtime.AbstractTokensProducer
[ERROR]         at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:210)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:205)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
[ERROR]         ... 16 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

This openAPI spec doesn't even have `security` tags, so all the authz classes should be skipped and not generated.

**Comment by ricardozanini** [comment]
@rmanibus, since you introduced this feature, do you mind taking a look and fixing it if possible?

**Comment by rmanibus** [comment]
Sure !

**Comment by ricardozanini** [comment]
@rmanibus do you have an estimate when you can take a look at it?

**Comment by rmanibus** [comment]
I tried to poke around already, I think I have a solution but I am still trying to find a solution to test it. I am not sure how I could remove an extension for a specific test.
I meant to ask this on zulip, but if you have an idea I am all ears !

**Comment by ricardozanini** [comment]
You can create a new `integration test` without the OIDC Client, and you will be able to reproduce this error. Then in the test case, you can just check if the Authz files were not generated.

**Comment by rmanibus** [comment]
I tried that already, but the oidc extension is included in the parent pom, and there is no way to exclude it

**Comment by ricardozanini** [comment]
You mean this https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/client/integration-tests/pom.xml#L71?

**Comment by rmanibus** [comment]
yes

**Comment by vhuc** [comment]
Il still have an issue with 2.6.0 and 2.6.0-lts linked, i think, with oidc client. I have this warning and after that, the test is blocked indefinitely : 
`2024-11-12 11:32:43,404 WARN  [io.qua.arc.pro.BeanArchives] (build-41) Failed to index io.quarkus.oidc.client.runtime.AbstractTokensProducer: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST for NameTest (QuarkusTest)@39329d81
`

**Comment by rmanibus** [comment]
Could you provide a reproducer ?

**Comment by oben01** [comment]
Same issue here 
`WARN  [io.qua.arc.pro.BeanArchives] (build-51) Failed to index io.quarkus.oidc.client.runtime.AbstractTokensProducer: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST for AskRessourceTest (QuarkusTest)`

Java 17 
Quarkus 3

You can reproduce it with a fresh Quarkus projets

**Comment by ricardozanini** [comment]
@rmanibus mind taking a look?

**Comment by ricardozanini** [comment]
@rmanibus, did you have the chance to take a look at it?

@Postremus I'm busy with #852. As soon as I fix it (it was more challenging than I first foresaw), I'll fix this one, too, if the original author of the feature cannot.

**Comment by rmanibus** [comment]
I will have a look over the weekend, sorry I am pretty busy this week !

**Comment by ricardozanini** [comment]
Reopening this issue since we are still getting many complains from the community after this change. I'll work on it this week cc @gastaldi

**Comment by ricardozanini** [comment]
Quarkus core issue: https://github.com/quarkusio/quarkus/issues/44689

**Comment by ricardozanini** [comment]
It seems that a few extensions are triggering this problem. The file `io.quarkus.oidc.client.runtime.AbstractTokensProducer` is being referenced only on a couple files in the runtime side. I'm doing a few tests here, should soon have a fix.

**Comment by vkn** [comment]
@ricardozanini works for me
