### ISSUE TITLE
oneOf still not working after update of openApiTools to 6.4.0

### ISSUE THREAD

**Issue by gcomte** [quarkiverse/quarkus-openapi-generator#287]
Related to https://github.com/quarkiverse/quarkus-openapi-generator/issues/120.

I still have an issue with `oneOf`, using OpenAPI Generator - v2.2.1 

Specifically I'm trying to generate a model for the [BTCPay API](https://docs.btcpayserver.org/API/Greenfield/v1/swagger.json), but I get the following error:
```
cannot find symbol
symbol:   class OneOfstringobject
```

**Comment by hbelmiro** [comment]
That's a bug in the library we use to generate the code.
I filed an issue: https://github.com/OpenAPITools/openapi-generator/issues/15044

**Comment by gastaldi** [comment]
I also get the same error when generating the code from https://github.com/zulip/zulip/blob/main/zerver/openapi/zulip.yaml
